site_name: AMSI Docs
docs_dir: 'docs/es'
site_dir: 'generated/es'

theme:
  name: material
  language: es
  custom_dir: 'overrides'
  logo: assets/logo.jpg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Canvia a mode fosc
      primary: custom
      accent: custom 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Canvia a mode clar
      primary: custom
      accent: custom

nav:
  - Inicio: index.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amsi-dev
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100010748358011
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/amsantisidre/
  alternate:
    - name: Valencià
      link: /va/
      lang: ca
    - name: Español
      link: /es/
      lang: es
    - name: English
      link: /en/
      lang: en

repo_url: https://github.com/amsi-dev/docu
repo_name: AMSI Docu

plugins:
  - search:
      lang: es
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      anchorlink: true
      baselevel: 1

copyright:
  2025 <a href="https://amsantisidre.es" target="_blank" rel="noopener">Agrupació Musical Sant Isidre</a>